services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: chaiminwoo0223/jijijig:latest
    container_name: spring-boot-app
    environment:
      DB_JDBC_URL: ${DB_JDBC_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_SECOND: ${ACCESS_SECOND}
      REFRESH_SECOND: ${REFRESH_SECOND}
      FIREBASE_KEY: ${FIREBASE_KEY}
      CHROME_DRIVER: ${CHROME_DRIVER}
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./firebase:/app/firebase
    networks:
      - jijijig-network

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: /bin/sh -c 'while :; do sleep 6h & wait $$!; nginx -s reload; done & nginx -g "daemon off;"'
    restart: always
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $$!; done;'"

networks:
  jijijig-network:
    driver: bridge